### ISSUE TITLE
how to install?

### ISSUE THREAD

**Issue by arielcavadia1** [bumbeishvili/coronavirus.davidb.dev#19]
Excellent work. How can I install this on a cpanel server?

**Comment by bumbeishvili** [comment]
Hello @arielcavadia1 , Sorry this repo was not meant to be installed on a separate server

Actual logic lies somewhere else and I am also using a paid private server, which is not public as well.

I published this repository to make it easy for people to change their home language translation texts

**Comment by arielcavadia1** [comment]
I understand. thanks for the clarification
