### ISSUE TITLE
Not Work

### ISSUE THREAD

**Issue by rafaelsabino** [bumbeishvili/coronavirus.davidb.dev#23]
Excellent idea, but I received errors when sending to the server. The errors are below, does anyone know how to solve them?

(index):1 Access to script at 'https://api.observablehq.com/http://app.brasilcontracovid19.com.br/.js' from origin 'http://app.brasilcontracovid19.com.br' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
api.observablehq.com/http://app.brasilcontracovid19.com.br/.js:1 Failed to load resource: net::ERR_FAILED
davidb-data.herokuapp.com/https://www.worldometers.info/coronavirus/:1 Failed to load resource: the server responded with a status of 403 (Forbidden)
cors-anywhere.herokuapp.com/https://davidb-data.herokuapp.com/https://www.worldometers.info/coronavirus/:1 Failed to load resource: the server responded with a status of 403 (Forbidden)
d3-fetch.min.js:2 Uncaught (in promise) Error: 403 Forbidden
    at o (d3-fetch.min.js:2)

**Comment by bumbeishvili** [comment]
Github is experiencing problems currently, that's why page not working, files are hosted on Github

**Comment by bumbeishvili** [comment]
If you want to install in your own server, then sorry this repo was not meant to be installed on a separate server

Actual logic lies somewhere else and I am also using a paid private server, which is not public as well.

I published this repository to make it easy for people to change their home language translation texts
