### ISSUE TITLE
Toggle to disable automatic translations

### ISSUE THREAD

**Issue by Igloczek** [bumbeishvili/coronavirus.davidb.dev#4]
First of all it's a really nice project!

I'd love to have an option to disable automatic translations, because as always there are cases where the translations are not perfect, so the easiest way is to fallback to English.

**Comment by bumbeishvili** [comment]
Hello @Igloczek , and thank you

Language switcher  in the interface is already planned, I will add it tomorrow probably

**Comment by bumbeishvili** [comment]
Correction - John Hopkins University stopped supplementing of recovered data. This raises more important issues than translations, now I have to maintain data as well, so I will probably switch to this, once data issue will be resolved

**Comment by bumbeishvili** [comment]
Now you can switch languages and it will be saved

![lang](https://user-images.githubusercontent.com/6873202/77652080-275e9700-6f87-11ea-9562-dbe7b8417bbc.gif)
